

```
# This is formatted as code
```
# datasets :

1.cibil [cumulated  by the various bank to the cibil body about the customers past loan history and there's a credit score and a 4 flags p1,p2,p3,p4 ]

total 60 features

2.Internal bank's data[bank of baroda]

In [ ]:
import pandas as pd

In [ ]:
df2=pd.read_excel('cibil.xlsx')

In [ ]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [ ]:
df1=pd.read_excel("banks_internal.xlsx")

In [ ]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32

#bank's internal product dataset
TL=termlines [ a loan account]
total_tl=total loan accounts active

total_tl_closed_l6m=total loan ccounts closed/ completed by customer in last 6 months

pct_tl_open_l6m= percent of total TL opened in last 6 months

secured_TL= loan with colateral

unsecured_tl=loan without colateral [high intrest rates]

In [ ]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

#cibil data set
deliquency =no of days a payment is overdue

num_times_deliquent= kitne bar overdue hua hee

max_deliquency=total no of months in deliquency

cc_enq= credit card enquiries [more enquires no good]

cc_utilization=which customer utilizes the card the most more utilization n ot good more utilization drops credit score

num_std=number of standard payment  made i.e payment made on time
 num_sub= payment made late but not considered as npa as the customer will eventuallu pay the loan


 based on the feature target description file  categories:

 30-41=deliquency data

 42-50 =payment types-standard, substandard, doubtful

 55-65=enquires :PP (personal loan), CC(credit card)

 66-71= genral info on customer

 72-82==CC utilization

 83-89=check in file as  these are mixed

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support
import warnings
import os

In [ ]:
df1.shape

(51336, 26)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PROSPECTID            51336 non-null  int64
 1   Total_TL              51336 non-null  int64
 2   Tot_Closed_TL         51336 non-null  int64
 3   Tot_Active_TL         51336 non-null  int64
 4   Total_TL_opened_L6M   51336 non-null  int64
 5   Tot_TL_closed_L6M     51336 non-null  int64
 6   pct_tl_open_L6M       51336 non-null  float64
 7   pct_tl_closed_L6M     51336 non-null  float64
 8   pct_active_tl         51336 non-null  float64
 9   pct_closed_tl         51336 non-null  float64
 10  Total_TL_opened_L12M  51336 non-null  int64
 11  Tot_TL_closed_L12M    51336 non-null  int64
 12  pct_tl_open_L12M      51336 non-null  float64
 13  pct_tl_closed_L12M    51336 non-null  float64
 14  Tot_Missed_Pmnt       51336 non-null  int64
 15  Auto_TL               51336 non-null  int64
 16  CC_TL                 51336 non-null  int64
 17  Consumer_TL           51336 non-null  int64
 18  Gold_TL               51336 non-null  int64
 19  Home_TL               51336 non-null  int64
 20  PL_TL                 51336 non-null  int64
 21  Secured_TL            51336 non-null  int64
 22  Unsecured_TL          51336 non-null  int64
 23  Other_TL              51336 non-null  int64
 24  Age_Oldest_TL         51336 non-null  int64
 25  Age_Newest_TL         51336 non-null  int64
dtypes: float64(6), int64(20)
memory usage: 10.2 MB

In [ ]:
df1=df1.loc[df1['Age_Oldest_TL']!=-99999]

In [ ]:
df1.shape

(51296, 26)

In [ ]:
df1=df1.loc[df1['Age_Newest_TL']!=99999]

In [ ]:
df1.shape

(51296, 26)

In [ ]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

now df2 has much null values than expected so our approach will be :

if the no of null values in a particular col is greater than 10000 we drop that column else if the no  of null values is less rtha 10000 we drop the rows

we are not going to impute as there are certainn sensitive cols which can be filled based on other customers data

In [ ]:
columns_to_be_dropped=[]
for col in df2.columns:
  if df2.loc[df2[col] == -99999].shape[0]>10000:
    columns_to_be_dropped.append(col)
columns_to_be_dropped

['time_since_first_deliquency',
 'time_since_recent_deliquency',
 'max_delinquency_level',
 'max_deliq_6mts',
 'max_deliq_12mts',
 'CC_utilization',
 'PL_utilization',
 'max_unsec_exposure_inPct']

droping the columns

In [ ]:
df2.drop(columns=columns_to_be_dropped,inplace=True) #df2.drop(colums_to_be dropped, axis=1) this can a;lso be used but inplace more efficient

In [ ]:
df2.shape

(51336, 54)

dropping the rows

loc is a label-based data selecting method in Pandas. You can use it to select rows and columns from a DataFrame using their labels or a boolean array.

In [ ]:
for i in df2.columns:
  df2=df2.loc[df2[i]!=-99999]

In [ ]:
df2.shape

(42066, 54)

In [ ]:
for i in list(df1.columns):
  if i in list(df2.columns):
    print(i)

PROSPECTID

now we will merge the df1 and df2 based on inner join as we mwill take intersection pf values of both dtaframe as we dont want nul values

In [ ]:
df=pd.merge(df1,df2,how='inner',left_on='PROSPECTID',right_on='PROSPECTID')

In [ ]:
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.0,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3

In [ ]:
df.shape

(42064, 79)

checking the no of columns with categorical value

In [ ]:
for i in df.columns:
  if df[i].dtype=='object':
    print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [ ]:
df['MARITALSTATUS'].value_counts()

MARITALSTATUS
Married    30886
Single     11178
Name: count, dtype: int64

now to check whether is marital status is related to approved flag or not we will use hypothesiss testing under which we can use the:

chisquare test , annova test ,t-test;


#Hypothesis testing
for two columns is a statistical method used to determine if there's a significant relationship or difference between the data in those columns.


#how the hypothesis testing works:

1.H0:null hypothesis:
not associated

2.H1: Alternate hypothesis:

associated

3.alpha(assumed):

significance level,
strictness level
,margin error

5%=0.05

less risky project = high alpha
less risky project-less alpha


4.confidence interval

1-alpha

5.calculate the evidence against HO

p-value [calculated using test chisquare , annova , t test ]

6.p-value<= alpha [ reject H0 ]

p-value> = alpha [fail to reject H0]

Descriptive statistics summarizes the main characteristics of a dataset, while inferential statistics uses that data to make predictions or generalizations about a larger population.

#Descriptive statistics describe the data you have. This includes things like:

Measures of central tendency: mean, median, mode.

Measures of spread: standard deviation, range, quartiles.

#Inferential statistics allows you to infer information about a population based on a sample. This includes:

Hypothesis testing: testing if a hypothesis about a population is true.

Confidence intervals: estimating a range of values for a population parameter.

Regression analysis: modeling the relationship between variables.

chi square test : whem there are two categorical columns

anova test : one numerical and one categorical and the no of categories are more than 3

t test : when  no of categories are 2

In [ ]:
#doing chi square test on categorical col to check whether they are important or not
for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval, _, _ = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)

MARITALSTATUS --- 3.578180861038862e-233
EDUCATION --- 2.6942265249737532e-30
GENDER --- 1.907936100186563e-05
last_prod_enq2 --- 0.0
first_prod_enq2 --- 7.84997610555419e-287

here we get the p values and all are less than alpha thus we accept all of them thus we include all categorical value

#now analysis on numerical columns
now we will check how each numerical col is associated with approved flag col using annova test as no of categories are more than  

but before chwecking that we can check how the numerical col are interaleted among themselves via mullticollinearity

In [ ]:
numerical_cols=[]
for i in df.columns:
  if df[i].dtype != 'object' and i not in ['PROSPECTID','Approved_Flag']:
    numerical_cols.append(i)

In [ ]:
numerical_cols
len(numerical_cols)

72

#multicollinearity vs multicorellation vs featureimportance

Correlation measures the linear relationship between two variables [input and output col ], while mutual information captures any kind of relationship, including non-linear ones.

Correlation: How well can you fit a straight line to the relationship between two variables

 Feature importance from mutual information identifies how much information a feature provides about the target variable. Higher mutual information suggests a stronger relationship, making it a good candidate for feature selection.

 Multicollinearity: [between input cols]

 here we check how the input cols are related to each other ..if there are too much related to each other that no good for model reliability


  Refers to a high correlation between two or more predictor variables in a regression model. This can make it difficult to determine the individual effect of each predictor on the outcome variable.

#multicolinearity

we calculate multicollineraity  using variance inflation factor

VIF (Variance Inflation Factor) is a common way to detect multicollinearity in regression analysis.

Here's how it works:

Calculate VIF for each predictor variable. VIF quantifies how much the variance of a regression coefficient is inflated due to multicollinearity.
Interpret VIF values.

VIF = 1: No multicollinearity.

VIF > 1: Some multicollinearity.

VIF > 5 or 10: Potentially problematic multicollinearity.

In [ ]:
# VIF sequentially check

vif_data = df[numerical_cols]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0



for i in range (0,total_columns):

    vif_value = variance_inflation_factor(vif_data, column_index)
    print (column_index,'---',vif_value)


    if vif_value <= 6:
        columns_to_be_kept.append( numerical_cols[i] )
        column_index = column_index+1

    else:
        vif_data = vif_data.drop([ numerical_cols[i] ] , axis=1)

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf
0 --- 11.320180023967996
0 --- 8.363698035000336
0 --- 6.520647877790928
0 --- 5.149501618212625
1 --- 2.611111040579735

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --- inf
2 --- 1788.7926256209232
2 --- 8.601028256477228
2 --- 3.832800792153077
3 --- 6.099653381646723
3 --- 5.581352009642766
4 --- 1.985584353098778

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 --- inf
5 --- 4.80953830281934
6 --- 23.270628983464636
6 --- 30.595522588100053
6 --- 4.384346405965583
7 --- 3.0646584155234238
8 --- 2.898639771299251
9 --- 4.377876915347324
10 --- 2.207853583695844
11 --- 4.916914200506864
12 --- 5.214702030064725
13 --- 3.3861625024231476
14 --- 7.840583309478997
14 --- 5.255034641721434

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 --- inf
15 --- 7.380634506427238
15 --- 1.4210050015175733
16 --- 8.083255010190316
16 --- 1.6241227524040114
17 --- 7.257811920140003
17 --- 15.59624383268298
17 --- 1.825857047132431
18 --- 1.5080839450032664
19 --- 2.172088834824578
20 --- 2.6233975535272274
21 --- 2.2959970812106176
22 --- 7.360578319196446
22 --- 2.1602387773102567
23 --- 2.8686288267891467
24 --- 6.458218003637272
24 --- 2.8474118865638247
25 --- 4.753198156284083
26 --- 16.22735475594825
26 --- 6.424377256363877
26 --- 8.887080381808678
26 --- 2.3804746142952653
27 --- 8.60951347651454
27 --- 13.06755093547673
27 --- 3.500040056654653
28 --- 1.9087955874813773
29 --- 17.006562234161628
29 --- 10.730485153719197
29 --- 2.3538497522950275
30 --- 22.10485591513649
30 --- 2.7971639638512924
31 --- 3.424171203217696
32 --- 10.175021454450922
32 --- 6.408710354561292
32 --- 1.001151196262563
33 --- 3.069197305397273
34 --- 2.8091261600643724
35 --- 20.249538381980678
35 --- 15.864576541593774
35 --- 1.833164974053215
36 --- 1.5680839909542046
37 --- 1.9307572353811682
38 --- 4.331265056645244
39 --- 9.390334396150173

here we did a sequential vif check instead of parallel in parallel we check the collinearity of each with all the input cols ...in sequential once a particular col is rejected on basis of its calculateed vif score i.e if its vif score > 6 [ have much collinearity and is not good ] it is removed and is not considered or is not used when calulatinfg collinearity of othe cols.

In [ ]:
columns_to_be_kept
len(columns_to_be_kept)

39

# annova test[now input to output cols]

In [ ]:
from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])
    b = list(df['Approved_Flag'])

    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']


    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value <= 0.05:
        columns_to_be_kept_numerical.append(i)

In [ ]:
columns_to_be_kept_numerical

['pct_tl_open_L6M',
 'pct_tl_closed_L6M',
 'Tot_TL_closed_L12M',
 'pct_tl_closed_L12M',
 'Tot_Missed_Pmnt',
 'CC_TL',
 'Home_TL',
 'PL_TL',
 'Secured_TL',
 'Unsecured_TL',
 'Other_TL',
 'Age_Oldest_TL',
 'Age_Newest_TL',
 'time_since_recent_payment',
 'max_recent_level_of_deliq',
 'num_deliq_6_12mts',
 'num_times_60p_dpd',
 'num_std_12mts',
 'num_sub',
 'num_sub_6mts',
 'num_sub_12mts',
 'num_dbt',
 'num_dbt_12mts',
 'num_lss',
 'recent_level_of_deliq',
 'CC_enq_L12m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L3m',
 'NETMONTHLYINCOME',
 'Time_With_Curr_Empr',
 'CC_Flag',
 'PL_Flag',
 'pct_PL_enq_L6m_of_ever',
 'pct_CC_enq_L6m_of_ever',
 'HL_Flag',
 'GL_Flag']

In [ ]:
len(columns_to_be_kept_numerical)

37

In [ ]:
features = columns_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']
df = df[features + ['Approved_Flag']]

In [ ]:
df.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,0.000,0.0,1,0,Married,12TH,M,PL,PL,P2
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others,P2
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL,P1
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL,P3

In [ ]:
df.to_csv('final_dataset_v1.csv')

In [ ]:
df.shape

(42064, 43)

In [ ]:
df.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,0.000,0.0,1,0,Married,12TH,M,PL,PL,P2
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others,P2
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL,P1
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL,P3

in chi square test if the p value is less than alpaha then strong connection
in chisquare contigency table os used nad annova f statistics table is used

In [ ]:
# #encoding the categorical value
# ordinal and one hot encoding
# now we will apply ordinal encoding education coll as it has hierarchy and one hot encoding for all other

In [ ]:
df['EDUCATION'].value_counts()

EDUCATION
GRADUATE          14140
12TH              11703
SSC                7241
UNDER GRADUATE     4572
OTHERS             2291
POST-GRADUATE      1898
PROFESSIONAL        219
Name: count, dtype: int64

In [ ]:
df1=df

In [ ]:
df['EDUCATION'].unique()

array(['12TH', 'GRADUATE', 'SSC', 'POST-GRADUATE', 'UNDER GRADUATE',
       'OTHERS', 'PROFESSIONAL'], dtype=object)

In [ ]:
#import pandas as pd

# Assuming your DataFrame is named 'df' and has an 'EDUCATION' column

# Create a dictionary mapping education levels to ordinal values
education_mapping = {
    '12TH':2, 'GRADUATE':3, 'SSC':1, 'POST-GRADUATE':4, 'UNDER GRADUATE':3,
       'OTHERS':1, 'PROFESSIONAL':3
}

# Apply the mapping to the 'EDUCATION' column using map()
df['EDUCATION'] = df['EDUCATION'].map(education_mapping)

# Now, create the OrdinalEncoder and fit_transform using the numerical values.
# ordinal_encoder = OrdinalEncoder(categories=[list(education_mapping.values())])  # Order of categories
# df['EDUCATION'] = ordinal_encoder.fit_transform(df[['EDUCATION']])



# Now you have a new column 'EDUCATION_encoded' with ordinal values

In [ ]:
df.head(

)

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,0.000,0.0,1,0,Married,2,M,PL,PL,P2
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,0.000,0.0,0,0,Single,3,F,ConsumerLoan,ConsumerLoan,P2
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,0.000,0.0,1,0,Married,1,M,ConsumerLoan,others,P2
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,0.000,0.0,0,0,Married,4,M,AL,AL,P1
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,0.429,0.0,1,0,Married,2,M,ConsumerLoan,PL,P3

In [ ]:
df['EDUCATION'].value_counts()

EDUCATION
3    18931
2    11703
1     9532
4     1898
Name: count, dtype: int64

In [ ]:
#now we will apply one hot on other categorical cols
df_encoded=pd.get_dummies(df,columns=['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2'])

In [ ]:
print(df.shape)
print(df_encoded.shape)

(42064, 43)
(42064, 55)

In [ ]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 55 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               42064 non-null  float64
 1   pct_tl_closed_L6M             42064 non-null  float64
 2   Tot_TL_closed_L12M            42064 non-null  int64
 3   pct_tl_closed_L12M            42064 non-null  float64
 4   Tot_Missed_Pmnt               42064 non-null  int64
 5   CC_TL                         42064 non-null  int64
 6   Home_TL                       42064 non-null  int64
 7   PL_TL                         42064 non-null  int64
 8   Secured_TL                    42064 non-null  int64
 9   Unsecured_TL                  42064 non-null  int64
 10  Other_TL                      42064 non-null  int64
 11  Age_Oldest_TL                 42064 non-null  int64
 12  Age_Newest_TL                 42064 non-null  int64
 13  time_since_recent_payment     42064 non-null  int64
 14  max_recent_level_of_deliq     42064 non-null  int64
 15  num_deliq_6_12mts             42064 non-null  int64
 16  num_times_60p_dpd             42064 non-null  int64
 17  num_std_12mts                 42064 non-null  int64
 18  num_sub                       42064 non-null  int64
 19  num_sub_6mts                  42064 non-null  int64
 20  num_sub_12mts                 42064 non-null  int64
 21  num_dbt                       42064 non-null  int64
 22  num_dbt_12mts                 42064 non-null  int64
 23  num_lss                       42064 non-null  int64
 24  recent_level_of_deliq         42064 non-null  int64
 25  CC_enq_L12m                   42064 non-null  int64
 26  PL_enq_L12m                   42064 non-null  int64
 27  time_since_recent_enq         42064 non-null  int64
 28  enq_L3m                       42064 non-null  int64
 29  NETMONTHLYINCOME              42064 non-null  int64
 30  Time_With_Curr_Empr           42064 non-null  int64
 31  CC_Flag                       42064 non-null  int64
 32  PL_Flag                       42064 non-null  int64
 33  pct_PL_enq_L6m_of_ever        42064 non-null  float64
 34  pct_CC_enq_L6m_of_ever        42064 non-null  float64
 35  HL_Flag                       42064 non-null  int64
 36  GL_Flag                       42064 non-null  int64
 37  EDUCATION                     42064 non-null  int64
 38  Approved_Flag                 42064 non-null  object
 39  MARITALSTATUS_Married         42064 non-null  bool
 40  MARITALSTATUS_Single          42064 non-null  bool
 41  GENDER_F                      42064 non-null  bool
 42  GENDER_M                      42064 non-null  bool
 43  last_prod_enq2_AL             42064 non-null  bool
 44  last_prod_enq2_CC             42064 non-null  bool
 45  last_prod_enq2_ConsumerLoan   42064 non-null  bool
 46  last_prod_enq2_HL             42064 non-null  bool
 47  last_prod_enq2_PL             42064 non-null  bool
 48  last_prod_enq2_others         42064 non-null  bool
 49  first_prod_enq2_AL            42064 non-null  bool
 50  first_prod_enq2_CC            42064 non-null  bool
 51  first_prod_enq2_ConsumerLoan  42064 non-null  bool
 52  first_prod_enq2_HL            42064 non-null  bool
 53  first_prod_enq2_PL            42064 non-null  bool
 54  first_prod_enq2_others        42064 non-null  bool
dtypes: bool(16), float64(5), int64(33), object(1)
memory usage: 13.2+ MB

Even though the Approved_Flag column was not explicitly encoded using methods like one-hot encoding, it can still be used for prediction in your code because the machine learning algorithms you used (RandomForestClassifier, XGBClassifier, and DecisionTreeClassifier) can handle categorical target variables.


In the case of XGBoost, you explicitly performed label encoding using LabelEncoder before fitting the model, ensuring that the target variable was properly handled.

For RandomForest and DecisionTree, the label encoding likely happened implicitly within the algorithm's implementation.

#runing initial baseline models ...then we will fine tune the best model

In [ ]:
y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )




x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)





rf_classifier = RandomForestClassifier(n_estimators = 200, random_state=42)





rf_classifier.fit(x_train, y_train)



y_pred = rf_classifier.predict(x_test)





accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy}')
print ()
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)


for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.7636990372043266

Class p1:
Precision: 0.8370457209847597
Recall: 0.7041420118343196
F1 Score: 0.7648634172469202

Class p2:
Precision: 0.7957519116397621
Recall: 0.9282457879088206
F1 Score: 0.856907593778591

Class p3:
Precision: 0.4423380726698262
Recall: 0.21132075471698114
F1 Score: 0.28600612870275793

Class p4:
Precision: 0.7178502879078695
Recall: 0.7269193391642371
F1 Score: 0.7223563495895703

In [ ]:
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

xgb_classifier = xgb.XGBClassifier(objective='multi:softmax',  num_class=4)



y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)




xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy:.2f}')
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.78

Class p1:
Precision: 0.823906083244397
Recall: 0.7613412228796844
F1 Score: 0.7913890312660175

Class p2:
Precision: 0.8255418233924413
Recall: 0.913577799801784
F1 Score: 0.8673315769665035

Class p3:
Precision: 0.4756380510440835
Recall: 0.30943396226415093
F1 Score: 0.37494284407864653

Class p4:
Precision: 0.7342386032977691
Recall: 0.7356656948493683
F1 Score: 0.7349514563106796

In [ ]:
from sklearn.tree import DecisionTreeClassifier


y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


dt_model = DecisionTreeClassifier(max_depth=20, min_samples_split=10)
dt_model.fit(x_train, y_train)
y_pred = dt_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.71

Class p1:
Precision: 0.723091976516634
Recall: 0.7287968441814595
F1 Score: 0.7259332023575639

Class p2:
Precision: 0.8118792599805258
Recall: 0.8263627353815659
F1 Score: 0.8190569744597249

Class p3:
Precision: 0.3430830039525692
Recall: 0.32754716981132076
F1 Score: 0.33513513513513515

Class p4:
Precision: 0.6478304742684158
Recall: 0.6239067055393586
F1 Score: 0.6356435643564357

In [ ]:
df_encoded['Approved_Flag'].value_counts()

Approved_Flag
P2    25452
P3     6440
P4     5264
P1     4908
Name: count, dtype: int64

In [ ]:
#if the data is imbalaned  so we can't rely on accuraccy we use recall and f1

we test our data on training data and then on test data ...........

testing  our
model on training data tells us wheter our model has learned or not i.e it tells us about underfitting

In [ ]:
df.shape

(42064, 43)

#when we do this tuneing we get best parameter and basis on that parameer we create our model final

In [ ]:
# Hyperparameter tuning in xgboost



# Based on risk appetite of the bank, you will suggest P1,P2,P3,P4 to the business end user








# # Hyperparameter tuning for xgboost (Used in the session)

# # Define the hyperparameter grid
# param_grid = {
#   'colsample_bytree': [0.1, 0.3, 0.5, 0.7, 0.9],
#   'learning_rate'   : [0.001, 0.01, 0.1, 1],
#   'max_depth'       : [3, 5, 8, 10],
#   'alpha'           : [1, 10, 100],
#   'n_estimators'    : [10,50,100]
# }

# index = 0

# answers_grid = {
#     'combination'       :[],
#     'train_Accuracy'    :[],
#     'test_Accuracy'     :[],
#     'colsample_bytree'  :[],
#     'learning_rate'     :[],
#     'max_depth'         :[],
#     'alpha'             :[],
#     'n_estimators'      :[]

#     }


# # Loop through each combination of hyperparameters
# for colsample_bytree in param_grid['colsample_bytree']:
#   for learning_rate in param_grid['learning_rate']:
#     for max_depth in param_grid['max_depth']:
#       for alpha in param_grid['alpha']:
#           for n_estimators in param_grid['n_estimators']:

#               index = index + 1

#               # Define and train the XGBoost model
#               model = xgb.XGBClassifier(objective='multi:softmax',
#                                        num_class=4,
#                                        colsample_bytree = colsample_bytree,
#                                        learning_rate = learning_rate,
#                                        max_depth = max_depth,
#                                        alpha = alpha,
#                                        n_estimators = n_estimators)



#               y = df_encoded['Approved_Flag']
#               x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

#               label_encoder = LabelEncoder()
#               y_encoded = label_encoder.fit_transform(y)


#               x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)


#               model.fit(x_train, y_train)



#               # Predict on training and testing sets
#               y_pred_train = model.predict(x_train)
#               y_pred_test = model.predict(x_test)


#               # Calculate train and test results

#               train_accuracy =  accuracy_score (y_train, y_pred_train)
#               test_accuracy  =  accuracy_score (y_test , y_pred_test)



#               # Include into the lists
#               answers_grid ['combination']   .append(index)
#               answers_grid ['train_Accuracy']    .append(train_accuracy)
#               answers_grid ['test_Accuracy']     .append(test_accuracy)
#               answers_grid ['colsample_bytree']   .append(colsample_bytree)
#               answers_grid ['learning_rate']      .append(learning_rate)
#               answers_grid ['max_depth']          .append(max_depth)
#               answers_grid ['alpha']              .append(alpha)
#               answers_grid ['n_estimators']       .append(n_estimators)


#               # Print results for this combination
#               print(f"Combination {index}")
#               print(f"colsample_bytree: {colsample_bytree}, learning_rate: {learning_rate}, max_depth: {max_depth}, alpha: {alpha}, n_estimators: {n_estimators}")
#               print(f"Train Accuracy: {train_accuracy:.2f}")
#               print(f"Test Accuracy : {test_accuracy :.2f}")
#               print("-" * 30)

In [ ]:
# model=xgb.XGBClassifier(objective='multi:softmax',  num_class=4,colsample_bytree=0.3,learning_rate=1,max_depth=3,alpha=1,n_estimators=100)

# y = df_encoded['Approved_Flag']
# x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


# label_encoder = LabelEncoder()
# y_encoded = label_encoder.fit_transform(y)


# x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)




# model.fit(x_train, y_train)
# y_pred = model.predict(x_test)

# accuracy = accuracy_score(y_test, y_pred)
# print ()
# print(f'Accuracy: {accuracy:.2f}')
# print ()

# precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

# for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
#     print(f"Class {v}:")
#     print(f"Precision: {precision[i]}")
#     print(f"Recall: {recall[i]}")
#     print(f"F1 Score: {f1_score[i]}")
#     print()

Accuracy: 0.77

Class p1:
Precision: 0.8320693391115926
Recall: 0.757396449704142
F1 Score: 0.7929788332472896

Class p2:
Precision: 0.8186170212765957
Recall: 0.915163528245788
F1 Score: 0.8642021525503042

Class p3:
Precision: 0.4471445929526124
Recall: 0.27773584905660376
F1 Score: 0.3426443202979516

Class p4:
Precision: 0.7302823758519961
Recall: 0.7288629737609329
F1 Score: 0.7295719844357976

In [ ]:
y_train_pred=model.predict(x_train)

print(np.unique(y_train_pred))
train_accuracy =  accuracy_score (y_train, y_train_pred)
print (train_accuracy)

[0 1 2 3]
0.8211643041811536

In [ ]:
df.shape

(42064, 43)

In [ ]:
df.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,0.000,0.0,1,0,Married,2,M,PL,PL,P2
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,0.000,0.0,0,0,Single,3,F,ConsumerLoan,ConsumerLoan,P2
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,0.000,0.0,1,0,Married,1,M,ConsumerLoan,others,P2
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,0.000,0.0,0,0,Married,4,M,AL,AL,P1
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,0.429,0.0,1,0,Married,2,M,ConsumerLoan,PL,P3

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
df1=pd.read_csv('final_dataset_v1.csv')

In [ ]:
df1.shape

(42064, 44)

In [ ]:
df1.head()

,Unnamed: 0,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,...,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,0,0.000,0.0,0,0.000,0,0,0,4,1,...,0.000,0.0,1,0,Married,12TH,M,PL,PL,P2
1,1,0.000,0.0,0,0.000,0,0,0,0,0,...,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,2,0.125,0.0,0,0.000,1,0,0,0,2,...,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others,P2
3,3,0.000,0.0,0,0.000,0,0,0,0,3,...,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL,P1
4,4,0.000,0.0,1,0.167,0,0,0,0,6,...,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL,P3

In [ ]:
df1=df1.drop(['Unnamed: 0'],axis=1)

In [ ]:
df1.shape

(42064, 43)

In [ ]:
df1.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,0.000,0.0,1,0,Married,12TH,M,PL,PL,P2
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others,P2
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL,P1
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL,P3

In [ ]:
df1['EDUCATION'].value_counts()

EDUCATION
GRADUATE          14140
12TH              11703
SSC                7241
UNDER GRADUATE     4572
OTHERS             2291
POST-GRADUATE      1898
PROFESSIONAL        219
Name: count, dtype: int64

In [ ]:
sample = df1[['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']].head()

In [ ]:
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.pipeline import Pipeline,make_pipeline

#final tuned model and pipeline for deployment

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import FunctionTransformer, LabelEncoder
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import xgboost as xgb

# Define mappings and indices
education_mapping = {'12TH': 2, 'GRADUATE': 3, 'SSC': 1, 'POST-GRADUATE': 4, 'UNDER GRADUATE': 3, 'OTHERS': 1, 'PROFESSIONAL': 3}
education_col_idx = 38
maritalstatus_col_idx = 37
gender_col_idx = 39
last_prod_enq2_col_idx = 40
first_prod_enq2_col_idx = 41
#expected_columns = pipe.named_steps['functiontransformer'].fit_transform(x_train).columns

# Preprocessing function with consistent dummy variable alignment
def preprocess(df):
    if isinstance(df, np.ndarray):
        df = pd.DataFrame(df)
    df.columns = list(range(df.shape[1]))  # Set default column indices

    # Apply mappings
    df[education_col_idx] = df[education_col_idx].map(education_mapping)

    # Dummy encode categorical columns with specified column names
    df = pd.get_dummies(df, columns=[maritalstatus_col_idx, gender_col_idx, last_prod_enq2_col_idx, first_prod_enq2_col_idx], drop_first=True)
    expected_columns = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
    34, 35, 36, 38, '37_Single', '39_M', '40_CC', '40_ConsumerLoan',
    '40_HL', '40_PL', '40_others', '41_CC', '41_ConsumerLoan', '41_HL',
    '41_PL', '41_others'
]
    # Ensuring the column order is consistent with training data by returning all expected columns
    for col in expected_columns:
        if col not in df.columns:
            df[col] = 0
    return df[expected_columns]  # Return in the expected order

# Preprocessor transformer
preprocessor = FunctionTransformer(preprocess)

# Define model
model = xgb.XGBClassifier(objective='multi:softmax', num_class=4, colsample_bytree=0.5, learning_rate=0.1, max_depth=10, alpha=3, n_estimators=300)

# Pipeline
pipe = make_pipeline(preprocessor, model)

# Example training data
 # Assume df1 is your DataFrame with labeled data
y = df1['Approved_Flag']
x = df1.drop(['Approved_Flag'], axis=1)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

# Fit the pipeline
pipe.fit(x_train, y_train)

# Capture expected feature names after preprocessing on training data
expected_columns = pipe.named_steps['functiontransformer'].fit_transform(x_train).columns
y_pred = pipe.predict(x_test)
y_train_pred = pipe.predict(x_train)
print(expected_columns)
print("Predicted values:", y_pred)
print("Value counts of y_pred:", np.bincount(y_pred))

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f'Accuracy: {accuracy:.2f}')
print(f'train_accuracy {train_accuracy}')

# Precision, recall, and F1 score
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)
for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

# New data for prediction

##sahi

Index([                0,                 1,                 2,
                       3,                 4,                 5,
                       6,                 7,                 8,
                       9,                10,                11,
                      12,                13,                14,
                      15,                16,                17,
                      18,                19,                20,
                      21,                22,                23,
                      24,                25,                26,
                      27,                28,                29,
                      30,                31,                32,
                      33,                34,                35,
                      36,                38,       '37_Single',
                  '39_M',           '40_CC', '40_ConsumerLoan',
                 '40_HL',           '40_PL',       '40_others',
                 '41_CC', '41_ConsumerLoan',           '41_HL',
                 '41_PL',       '41_others'],
      dtype='object')
Predicted values: [1 3 1 ... 2 1 3]
Value counts of y_pred: [ 938 5595  829 1051]
Accuracy: 0.77
train_accuracy 0.9643695581112003
Class p1:
Precision: 0.8272921108742004
Recall: 0.7652859960552268
F1 Score: 0.7950819672131147

Class p2:
Precision: 0.8223413762287757
Recall: 0.9119920713577799
F1 Score: 0.8648496240601504

Class p3:
Precision: 0.4499396863691194
Recall: 0.28150943396226413
F1 Score: 0.3463324048282266

Class p4:
Precision: 0.7202664129400571
Recall: 0.7356656948493683
F1 Score: 0.7278846153846154

#Testing the model

In [ ]:
test = np.array([
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 16, 16, 424, 38, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    38, 0, 0, 108, 0, 18000, 122, 0, 0, 0, 0, 0, 0, 'Married', 'SSC', 'F', 'ConsumerLoan', 'others'
], dtype=object).reshape(1, 42)

# Prepare the test DataFrame with appropriate columns
test_df = pd.DataFrame(test, columns=list(range(42)))

# Convert numeric and categorical types
for col in range(37):
    test_df[col] = pd.to_numeric(test_df[col], errors='coerce')
test_df[37] = test_df[37].astype(str)
test_df[38] = test_df[38].astype(str)
test_df[39] = test_df[39].astype(str)
test_df[40] = test_df[40].astype(str)
test_df[41] = test_df[41].astype(str)

# Apply preprocessing on test data
processed_test_df = preprocess(test_df)

# Predict with the pipeline
predictions = pipe.predict(processed_test_df)
print("Predictions:", predictions)
##sahi

Predictions: [2]

In [ ]:
pip install joblib

In [ ]:
import joblib

# Save the entire pipeline to a file
joblib.dump(pipe, 'model.joblib')

In [ ]:
# from sklearn.preprocessing import FunctionTransformer
# from sklearn.compose import ColumnTransformer
# import pandas as pd

# # Mapping for 'EDUCATION' column
# education_mapping = {'12TH': 2, 'GRADUATE': 3, 'SSC': 1, 'POST-GRADUATE': 4, 'UNDER GRADUATE': 3, 'OTHERS': 1, 'PROFESSIONAL': 3}
# education_col_idx = 38  # Index for 'EDUCATION' column
# maritalstatus_col_idx = 37  # Index for 'MARITALSTATUS' column
# gender_col_idx = 39  # Index for 'GENDER' column
# last_prod_enq2_col_idx = 40  # Index for 'last_prod_enq2' column
# first_prod_enq2_col_idx = 41  # Index for 'first_prod_enq2' column

# # Mapping for 'EDUCATION' column
# education_mapping = {'12TH': 2, 'GRADUATE': 3, 'SSC': 1, 'POST-GRADUATE': 4, 'UNDER GRADUATE': 3, 'OTHERS': 1, 'PROFESSIONAL': 3}

# def preprocess(df):
#     # Convert input to DataFrame if it's a NumPy array
#     if isinstance(df, np.ndarray):
#         df = pd.DataFrame(df)

#     # Rename columns to a known schema based on indices
#     df.columns = list(range(df.shape[1]))

#     # Apply the 'EDUCATION' mapping
#     df[education_col_idx] = df[education_col_idx].map(education_mapping)

#     # Convert specified columns to dummy variables
#     df = pd.get_dummies(df, columns=[maritalstatus_col_idx, gender_col_idx, last_prod_enq2_col_idx, first_prod_enq2_col_idx], drop_first=True)

#     return df

# # Preprocessor
# preprocessor = FunctionTransformer(preprocess)

# # Model
# model = xgb.XGBClassifier(objective='multi:softmax', num_class=4, colsample_bytree=0.3, learning_rate=1, max_depth=3, alpha=1, n_estimators=100)

# # Make a pipeline
# pipe = make_pipeline(preprocessor, model)

# # Train-test split
# y = df1['Approved_Flag']
# x = df1.drop(['Approved_Flag'], axis=1)
# label_encoder = LabelEncoder()
# y_encoded = label_encoder.fit_transform(y)
# x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

# # Fit and predict
# pipe.fit(x_train, y_train)
# expected_columns = pipe.named_steps['functiontransformer'].fit_transform(x_train).columns
# y_pred = pipe.predict(x_test)
# print("Predicted values:", y_pred)
# print("Value counts of y_pred:", np.bincount(y_pred))

# # Evaluate accuracy
# accuracy = accuracy_score(y_test, y_pred)
# print(f'Accuracy: {accuracy:.2f}')

# # Precision, recall, and F1 score
# precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)
# for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
#     print(f"Class {v}:")
#     print(f"Precision: {precision[i]}")
#     print(f"Recall: {recall[i]}")
#     print(f"F1 Score: {f1_score[i]}")
#     print()

In [ ]:
# import numpy as np
# import pandas as pd

# # Sample input as an array
# test = np.array([
#     0, 0, 1, 0.167, 0, 0, 0, 0, 6, 0, 0, 150, 17, 245, 270, 0, 11, 2, 3, 0, 1, 0, 0, 0,
#     26, 1, 3, 7, 4, 0, 154, 0, 0, 0.429, 0, 1, 0, 'Married', '12TH', 'M', 'ConsumerLoan', 'PL'
# ], dtype=object).reshape(1, 42)

# # Convert test data into a DataFrame and set columns as expected by `preprocess`
# test_df = pd.DataFrame(test, columns=list(range(42)))

# # Manually set the data types for numeric and categorical columns
# for col in range(37):
#     test_df[col] = pd.to_numeric(test_df[col], errors='coerce')

# test_df[37] = test_df[37].astype(str)  # 'MARITALSTATUS'
# test_df[38] = test_df[38].astype(str)  # 'EDUCATION'
# test_df[39] = test_df[39].astype(str)  # 'GENDER'
# test_df[40] = test_df[40].astype(str)  # 'last_prod_enq2'
# test_df[41] = test_df[41].astype(str)  # 'first_prod_enq2'

# # Apply the preprocessing function to create dummy variables
# # processed_test_df = preprocess(test_df)

# # # # Fit the pipeline on training data and get feature names
# # pipe.fit(x_train, y_train)
# # expected_columns = pipe.named_steps['functiontransformer'].fit_transform(x_train).columns

# # # Add missing columns to processed_test_df and reorder columns to match training data
# # for col in expected_columns:
# #     if col not in processed_test_df.columns:
# #         processed_test_df[col] = 0

# # Reorder columns to match the expected structure
# # processed_test_df = processed_test_df[expected_columns]

# # Make predictions
# predictions = pipe.predict(test_df)
# print(predictions)

In [ ]:
test=np.array([0,0,1,0.167,0,0,0,0,6,0,0,150,17,245,270,0,11,2,3,0,1,0,0,0,26,1,3,7,4,0,154,0,0,0.429,0,1,0,'Married','12TH','M','ConsumerLoan','PL'],dtype=object).reshape(1,42)
print(pipe.predict(test))

In [ ]:
sample1=[0,0,1,0.167,0,0,0,0,6,0,0,150,17,245,270,0,11,2,3,0,1,0,0,0,26,1,3,7,4,0,154,0,0,0.429,0,1,0,'Married','12TH','M','ConsumerLoan','PL']
print(pipe.predict(sample1))

In [ ]:
import joblib

# Save the pipeline with joblib
joblib.dump(pipe, 'model_pipeline.joblib')

In [ ]:
# # Later, load the pipeline and make predictions
# with open('model_pipeline.pkl', 'rb') as f:
#     loaded_pipeline = pickle.load(f)

# # Now you can use loaded_pipeline directly on new data
# new_predictions = loaded_pipeline.predict(new_data)

In [ ]:
# from sklearn.pipeline import Pipeline,make_pipeline
# y = df1['Approved_Flag']
# x = df1.drop(['Approved_Flag'], axis=1)
# label_encoder = LabelEncoder()
# y_encoded = label_encoder.fit_transform(y)
# #
# # # Check the unique values in the original y column
# # print("Unique values in 'Approved_Flag':", df1['Approved_Flag'].unique())
# # print(df1['Approved_Flag'].value_counts())
# # # Check the unique values after encoding
# # print("Unique values in encoded target:", np.unique(y_encoded))
# print(np.bincount(y_encoded))


# # Train-test split
# x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)
# categories = [['OTHERS', 'SSC', '12TH', 'GRADUATE', 'UNDER GRADUATE', 'PROFESSIONAL', 'POST-GRADUATE']]
# preprocessor = ColumnTransformer([
#     ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [37, 39, 40, 41]),
#     ('ordinal', OrdinalEncoder(categories=categories, dtype=int), [38])
# ])

# # Define the model
# model = xgb.XGBClassifier(objective='multi:softmax', num_class=4, colsample_bytree=0.3,
#                       learning_rate=0.1, max_depth=3, alpha=10, n_estimators=100)

# # Make a pipeline with preprocessing and model
# pipe = make_pipeline(preprocessor, model)

# # Prepare the target variable
# # y = df1['Approved_Flag']
# # x = df1.drop(['Approved_Flag'], axis=1)
# # label_encoder = LabelEncoder()
# # y_encoded = label_encoder.fit_transform(y)

# # # Train-test split
# # x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

# # Fit the pipeline
# pipe.fit(x_train, y_train)

In [ ]:

# x_train.head()

In [ ]:
# df1.shape

In [ ]:
# x_train.shape

In [ ]:
# y_pred = pipe.predict(x_test)
# print(y_pred)
# print(np.unique(y_pred))
# accuracy = accuracy_score(y_test, y_pred)
# print ()
# print(f'Accuracy: {accuracy:.2f}')
# print ()

In [ ]:
# trf1 = ColumnTransformer([('_', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [38,40, 41,42])])

In [ ]:

# transformed_sample = trf1.fit_transform(sample)
# print(transformed_sample)
# trf1.fit(df1)  # Fit to the entire DataFrame to get all categories

# # Get feature names
# feature_names = trf1.get_feature_names_out(input_features=df1.columns)

# # Print the feature names
# print(feature_names)

# # Optionally, create a new DataFrame with transformed data and new column names
# transformed_df = pd.DataFrame(trf1.transform(df), columns=feature_names)

In [ ]:
# categories = [['OTHERS', 'SSC', '12TH', 'GRADUATE', 'UNDER GRADUATE', 'PROFESSIONAL', 'POST-GRADUATE']]
# trf2 = ColumnTransformer(
#     [('_', OrdinalEncoder(categories=categories, dtype=int), [39])]  # Specify dtype=int here
# )

In [ ]:
# sample=df1[['EDUCATION']].head()
# # sample['EDUCATION'] = sample['EDUCATION'].astype(str)
# trf2.fit(sample)
# transformed_sample = trf2.transform(sample)
# encoded_df = pd.DataFrame(transformed_sample, columns=['Encoded_Education'], index=sample.index)

# # Concatenate original and encoded data for comparison
# comparison_df = pd.concat([sample, encoded_df], axis=1)

# # Display the comparison DataFrame
# print(f"Encoded Data with Original Values:\n{comparison_df.head()}")

In [ ]:
# trf3=xgb.XGBClassifier(objective='multi:softmax',  num_class=4,colsample_bytree=0.3,learning_rate=1,max_depth=3,alpha=1,n_estimators=100)

In [ ]:
# from sklearn.pipeline import Pipeline,make_pipeline

In [ ]:
# y = df1['Approved_Flag']
# x = df1. drop ( ['Approved_Flag'], axis = 1 )


# label_encoder = LabelEncoder()
# y_encoded = label_encoder.fit_transform(y)


# x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

In [ ]:
# x_train.shape

In [ ]:
# columns = x.columns

# # Modify the pipeline to include ArrayToDataFrame
# pipe = make_pipeline(
#     # Convert NumPy array to DataFrame
#     trf1,
#     trf2,
#     trf3
# )
# x_train.head()

# pipe.fit(x_train, y_train)
# # y_pred = pipe.predict(x_test)

# # accuracy = accuracy_score(y_test, y_pred)
# # print ()
# # print(f'Accuracy: {accuracy:.2f}')
# # print ()

In [ ]:
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
# from sklearn.compose import ColumnTransformer
# model=xgb.XGBClassifier(objective='multi:softmax',  num_class=4,colsample_bytree=0.3,learning_rate=1,max_depth=3,alpha=1,n_estimators=100)
# # Define the ordinal encoder with the specified categories
# education_categories = [['OTHERS', 'SSC', '12TH', 'GRADUATE', 'UNDER GRADUATE', 'PROFESSIONAL', 'POST-GRADUATE']]  # Order of categories
# ordinal_encoder = OrdinalEncoder(categories=education_categories)

# # Fit and transform the 'EDUCATION' column
# df['EDUCATION'] = ord inal_encoder.fit_transform(df[['EDUCATION']])

# encoder = OneHotEncoder(sparse_output=False)
# encoded_data = encoder.fit_transform(df[['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']])
# feature_names = encoder.get_feature_names_out(['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2'])
# encoded_df = pd.DataFrame(encoded_data, columns=feature_names)
# df = df.drop(['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2'], axis=1)
# df = pd.concat([df, encoded_df], axis=1)
# df.shape
# Define transformations
# preprocessor = ColumnTransformer(
#     transformers=[
#         ('ord', ordinal_encoder(), ['EDUCATION']),
#         ('onehot', encoder(), ['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2'])
#     ],
#     remainder='passthrough'  # Keep other columns as is
# )

# # Build pipeline
# model_pipeline = Pipeline(steps=[
#     ('preprocessor', preprocessor),
#     ('model', model)
# ])

# # Train pipeline
# model_pipeline.fit(X_train, y_train)